# -*- coding: utf-8 -*-
"""04-02-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHAYd6slXAXx_Cd3VzBUCNlAMI8iLubi
"""

sentence=input()

exit_words=['esc','quit','stop','exit']

def lowercase(sent):
  return sent.lower()

lowercase(sentence)

def uppercase(sent):
  return sent.upper()

uppercase(sentence)

def swapcase(sent):
  return sent.swapcase()

swapcase(sentence)

import string

def remove_punctuation(text):
    """Removes punctuation from the given text."""
    return text.translate(str.maketrans('', '', string.punctuation))

# Example usage

# Output: Hello world Hows it going

remove_punctuation(sentence)

x=input()
while x not in exit_words:
  choice=input("enter your choice 1 or 2 or 3 or 4:")
  if choice=='1':
    print(lowercase(x))
  elif choice=='2':
    print(uppercase(x))
  elif choice=='3':
    print(swapcase(x))
  elif choice=='4':
    print(remove_punctuation(x))
  else:
    print("invalid")
  x=input()

