# -*- coding: utf-8 -*-
"""24-01-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BQZgdf9gU4IsuZlJNuTvwIyscU0y7fX
"""

import spacy
nlp=spacy.load('en_core_web_sm')

s='This is the sample sentence to check the spacy'

type(s)

s=nlp('This is a test sentence')
type(s)

s="This is u.s country.welcome here "
s.split('.')

s=nlp("This is u.s country.welcome here ")
for sentence in s.sents:
    print(sentence)

for word in s:
  print(f"{word}-{word.pos_}")

#stemming vs lemmatization
s=nlp('the boy is running while talking in the phone while calling friend for the party indexes')
for word in s:

  print(f"{word}-{word.lemma_}")

text =nlp( "When Yasasri started working in USA Chicago on self-driving cars at Google in 2007, few people outside of the company at google took him seriously.")
for word in text.ents:
  print(f"{word}-{word.label_}")
  print(word)

from spacy import displacy
displacy.serve(text,style="ent")

