# -*- coding: utf-8 -*-
"""DAY_15,18_ASSIGNMENTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Scu32Y3wGHC3JnkFpb1nEh2wVS4N9Vi7
"""

import re

def extract_emails(text):
    """
    Extract all email addresses from the given text using regular expressions.

    Args:
        text (str): The input string containing email addresses.

    Returns:
        list: A list of extracted email addresses.
    """
    # Define the regular expression for matching email addresses
    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    # Use re.findall to extract all matching email addresses
    return re.findall(email_pattern, text)

# Test case
test_string = 'Contact us at support@example.com and sales@example.org.'
emails = extract_emails(test_string)
print("Extracted emails:", emails)

import requests
from bs4 import BeautifulSoup

def fetch_webpage_title(url):
    """
    Fetches and prints the title of a webpage.

    Args:
        url (str): The URL of the webpage to fetch.
    """
    try:
        # Send a GET request to the URL
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for HTTP errors

        # Parse the webpage content
        soup = BeautifulSoup(response.text, 'html.parser')

        # Extract the title tag
        title = soup.title.string if soup.title else "No title found"
        print(f"Title of the webpage: {title}")
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the webpage: {e}")

# Test case
test_url = 'https://example.com'
fetch_webpage_title(test_url)