# -*- coding: utf-8 -*-
"""day_9,10 assignments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6Bhqg-U8VH5pxiyKDNLcUma4UDKrT3N
"""

#day9 assignment
import re

def clean_text(text):
    """
    Cleans the input text by removing special characters and converting it to lowercase.

    Args:
        text (str): The input text to be cleaned.

    Returns:
        str: The cleaned text.
    """
    # Convert text to lowercase
    text = text.lower()

    # Remove special characters using regex
    text = re.sub(r'[^a-z0-9\s]', '', text)

    return text

# Test the function
input_text = 'Hello, World! Welcome to NLP 101.'
cleaned_text = clean_text(input_text)

print("Original Text:")
print(input_text)
print("\nCleaned Text:")
print(cleaned_text)

#day10 assignment
import re

def extract_emails(text):
    """
    Extracts all email addresses from the given text using regular expressions.

    Args:
        text (str): The input text containing email addresses.

    Returns:
        list: A list of extracted email addresses.
    """
    # Regular expression for matching email addresses
    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

    # Find all matches in the text
    emails = re.findall(email_pattern, text)

    return emails

# Test the function
input_text = 'Contact us at support@example.com and sales@example.org.'
extracted_emails = extract_emails(input_text)

print("Original Text:")
print(input_text)
print("\nExtracted Emails:")
print(extracted_emails)