# -*- coding: utf-8 -*-
"""day 28,30 assignments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCYOX7ogBW3dMkOQIyvC8u-bolOK_gLM
"""

#day28 assignment
import spacy

# Load the SpaCy English model
nlp = spacy.load("en_core_web_sm")

# Function to perform NER
def named_entity_recognition(text):
    # Process the text using the NLP model
    doc = nlp(text)

    # Extract entities and their types
    print("Named Entities and Their Types:")
    for ent in doc.ents:
        print(f"{ent.text} ({ent.label_})")

# Example usage
text = """
Barack Obama was born on August 4, 1961, in Honolulu, Hawaii.
He served as the 44th president of the United States from 2009 to 2017.
Microsoft Corporation is headquartered in Redmond, Washington.
"""

named_entity_recognition(text)

#day30 assignment
from textblob import TextBlob

# Function to perform sentiment analysis
def sentiment_analysis(text):
    # Create a TextBlob object
    blob = TextBlob(text)

    # Get the sentiment polarity
    polarity = blob.sentiment.polarity

    # Determine the sentiment category
    if polarity > 0:
        sentiment = "Positive"
    elif polarity < 0:
        sentiment = "Negative"
    else:
        sentiment = "Neutral"

    # Display the result
    print(f"Text: {text}")
    print(f"Sentiment Polarity: {polarity:.2f}")
    print(f"Overall Sentiment: {sentiment}")

# Example usage
text = "I absolutely love this product! It's fantastic and works perfectly."
sentiment_analysis(text)

text2 = "The service was terrible, and I had an awful experience."
sentiment_analysis(text2)

text3 = "The product is okay, nothing special but not bad either."
sentiment_analysis(text3)