# -*- coding: utf-8 -*-
"""DAY 24,26 ASSIGNMENTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P47Oq1FRcxISXKvVqPWNIk4p-KXcuT_p
"""

#day24 assignment
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from collections import Counter

# Download the necessary NLTK data files (run this only once)
nltk.download('punkt')
nltk.download('punkt_tab') # Download the 'punkt_tab' data package

# Load the text file
def load_text(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()
    return text

# Tokenize the text and display the most common words
def analyze_text(file_path):
    text = load_text(file_path)
    tokens = word_tokenize(text.lower())  # Tokenize and convert to lowercase
    words = [word for word in tokens if word.isalnum()]  # Keep only alphanumeric tokens

    # Calculate word frequency
    word_freq = Counter(words)
    most_common_words = word_freq.most_common(10)

    print("10 Most Common Words:")
    for word, freq in most_common_words:
        print(f"{word}: {freq}")

# Replace 'sample.txt' with the path to your text file
file_path = '/content/textdata.txt'
analyze_text(file_path)

#day 26 assignment
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Function to calculate cosine similarity between two strings
def calculate_cosine_similarity(text1, text2):
    # Create a TfidfVectorizer object
    vectorizer = TfidfVectorizer()

    # Transform the text data into TF-IDF vectors
    tfidf_matrix = vectorizer.fit_transform([text1, text2])

    # Calculate the cosine similarity
    similarity = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

    return similarity[0][0]

# Example usage
string1 = "Text similarity calculation is important for NLP tasks."
string2 = "Calculating text similarity is crucial for natural language processing."

cosine_sim = calculate_cosine_similarity(string1, string2)
print(f"Cosine Similarity: {cosine_sim:.4f}")