# -*- coding: utf-8 -*-
"""DAY 32 ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfswRg-MjwMOxjfAAQZefk_tZamzzUfa
"""

import nltk
from nltk.tokenize import word_tokenize
from collections import Counter
import string

def load_text_file(file_path):
    """Loads a text file and returns its content."""
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read()

def preprocess_text(text):
    """Tokenizes text and removes punctuation."""
    tokens = word_tokenize(text.lower())  # Convert to lowercase
    tokens = [word for word in tokens if word.isalnum()]  # Remove punctuation
    return tokens

def compute_term_frequency(tokens):
    """Computes term frequency of tokens."""
    return Counter(tokens)

def main():
    file_path = "/content/sample_text.txt"  # Replace with your file path
    text = load_text_file(file_path)
    tokens = preprocess_text(text)
    tf = compute_term_frequency(tokens)

    print("Top 5 most frequent tokens:")
    for word, freq in tf.most_common(5):
        print(f"{word}: {freq}")

if __name__ == "__main__":
    nltk.download('punkt')
    nltk.download('punkt_tab')  # Ensure nltk tokenizer is available
    main()

