# -*- coding: utf-8 -*-
"""day_20,22_assignments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12T53UCRhoVVc9Xo4O48vfbPERvJPSmjh
"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

def generate_wordcloud(text, output_file):
    """
    Generates a WordCloud from the given text and saves it as an image.

    Args:
        text (str): The input text to generate the WordCloud.
        output_file (str): The file path to save the WordCloud image.
    """
    # Generate the WordCloud
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

    # Save the WordCloud image
    wordcloud.to_file(output_file)
    print(f"WordCloud saved as: {output_file}")

    # Display the WordCloud
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.show()

# Input text
text = 'data science machine learning artificial intelligence'

# Output image file
output_file = 'wordcloud.png'

# Generate and save the WordCloud
generate_wordcloud(text, output_file)

import spacy

def pos_tagging(sentence):
    """
    Performs part-of-speech tagging on the given sentence using SpaCy.

    Args:
        sentence (str): The input sentence for POS tagging.

    Returns:
        None
    """
    # Load the SpaCy English model
    nlp = spacy.load("en_core_web_sm")

    # Process the sentence
    doc = nlp(sentence)

    # Print each token with its corresponding POS tag
    print(f"{'Token':<15} {'POS Tag':<15} {'Description'}")
    print("-" * 40)
    for token in doc:
        print(f"{token.text:<15} {token.pos_:<15} {spacy.explain(token.pos_)}")

# Input sentence
sentence = 'NLP is amazing and fun to learn.'

# Perform POS tagging
pos_tagging(sentence)