# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7pzZpQsYJ1awNgv_xqoQIru-c80sJQz
"""

a=5
print(a)

a=[1,3.4,'hi']
print(a)

a.append(3.65)

print(a)

a.pop(1)

print(a)

b=3.65
a[1]=b
print(a)

b=5
a.insert(b,[2])
print(a)

a.insert(2,5.98)
print(a)

a[1]=3.4
print(a)

c=[3,4]
print(a+c)

print(a[2:4])

print(a[-5:-1])

print(a[:-2])

print(a[:])

