# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7FoH2_g5zfINPz-5gZEXQw_YZ32I79K
"""

#functions
#two types
#1.built-in
#2.user defined
print(dir(str))

a='Hello WOrld'
b=a.upper()
print(b)
print(a.lower())
print(a.title())

a="hello world"
b=a.replace('hello','hi')
print(b)
print(a.isdigit())

#functions can be called independently but methods should be call with object using(.) notation
a='12345'
print(a.isdigit())

a=range(10)
print(a)

a=range(10)
b=list(a)
print(b)

#slicing contains of start stop and steps
my_list=list(range(5,15,2))
print(my_list)

#function with returns
def add_numbers(a,b):
  result=a+b
  return result
add_numbers(1,7)

#function with default values
def greet(name,greeting="hello"):
  print(f"{greeting},{name}!")
greet('ram')

#function with args
def calculate_sum(*args):
  total=sum(args)
  return total
print("The sum is",calculate_sum(1,2,3,4,5))
print("sum:",calculate_sum(1,7,6))

#creating a program and adding 2 or more features to it
#predefined correct username and password
Correct_username="admin"
Correct_password="1234"
while True:
#prompt the user to get input
  username=input("Enter your name:")
  password=input("Enter your password:")
  if username==Correct_username and password==Correct_password:
    print("Login successful")
    break
  else:
    print("Invalid credentials")

print(dir(str))

def multiply_numbers(a,b):
  result=a*b
  return result
multiply_numbers(5,10)

a="hello   world"
print(a.isspace())

a="hello"
print(a.removesuffix("o"))

a=[1,22,"hi",3.56]
a.remove(22)
print(a)

# Built-in function: len()
my_list = [1, 2, 3, 4, 5]
length = len(my_list)
print(f"The length of the list is: {length}")

# Built-in function: max()
numbers = [4, 9, 1, 12, 6]
largest_number = max(numbers)
print(f"The largest number in the list is: {largest_number}")

# User-defined function: calculate_factorial()
def calculate_factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * calculate_factorial(n - 1)

# Testing the user-defined function
num = 5
result = calculate_factorial(num)
print(f"The factorial of {num} is: {result}")